version: '3.8'
services:
  portal:
    image: quickplaymod/quickplay-portal-build-stage
    depends_on:
      - db
      - redis
      - socket
    ports:
      - "43515:80"
      - "5860:5860"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run serve
    env_file:
      - .env
  socket:
    depends_on:
      - db
      - redis
    image: quickplaymod/quickplay-socket
    ports:
      - "54678:80"
    restart: unless-stopped
    volumes:
      - ../glyphs-volume:/usr/src/app/glyphs
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    env_file:
      - socket.env
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ../redis-volume:/var/lib/redis
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ../db-volume:/var/lib/mysql
    env_file:
      - docker-db.env
